class ChairTester{
	public static void main(String s[]){
		//object creation in java
		//ClassName referenceVariable = new ClassName();
		Chair chair = new Chair();
		chair.name="Nirmala";
		chair.type="Plastic";
		chair.color="Cream";
		chair.price=300.00;
		chair.toSit();
		System.out.println(chair.name+"\n"+chair.type+"\n"+chair.color+"\n"+chair.price);
		Chair chair1 = new Chair();
		chair1.name="Platina";
		chair1.type="Fibre";
		chair1.color="White";
		chair1.price=500.00;
		chair1.toSit();
		System.out.println(chair1.name+"\n"+chair1.type+"\n"+chair1.color+"\n"+chair1.price);
		Chair chair2 = new Chair();
		chair2.name="Kamala";
		chair2.type="Metal";
		chair2.color="Gray";
		chair2.price=800.00;
		chair2.toSit();
		System.out.println(chair2.name+"\n"+chair2.type+"\n"+chair2.color+"\n"+chair2.price);
		Chair chair3 = new Chair();
		chair3.name="Classic Elegance";
		chair3.type="Wooden";
		chair3.color="Mahogany";
		chair3.price=2500.00;
		chair3.toSit();
		System.out.println(chair3.name+"\n"+chair3.type+"\n"+chair3.color+"\n"+chair3.price);
		Chair chair4 = new Chair();
		chair4.name="Cozy Comfort";
		chair4.type="Upholster";
		chair4.color="Gray";
		chair4.price=1800.00;
		chair4.toSit();
		System.out.println(chair4.name+"\n"+chair4.type+"\n"+chair4.color+"\n"+chair4.price);
		Chair chair5 = new Chair();
		chair5.name="Vintage Charm";
		chair5.type="Leather";
		chair5.color="Brown";
		chair5.price=4000.00;
		chair5.toSit();
		System.out.println(chair5.name+"\n"+chair5.type+"\n"+chair5.color+"\n"+chair5.price);
		Chair chair6 = new Chair();
		chair6.name="Industrial Loft";
		chair6.type="Metal";
		chair6.color="Black";
		chair6.price=1200.00;
		chair6.toSit();
		System.out.println(chair6.name+"\n"+chair6.type+"\n"+chair6.color+"\n"+chair6.price);
		Chair chair7 = new Chair();
		chair7.name="Modern Minimalist";
		chair7.type="Acrylic";
		chair7.color="Transparent";
		chair7.price=3500.00;
		chair7.toSit();
		System.out.println(chair7.name+"\n"+chair7.type+"\n"+chair7.color+"\n"+chair7.price);
		Chair chair8 = new Chair();
		chair8.name="Lounge Deluxe";
		chair8.type="Chaise Lounge";
		chair8.color="Navy Blue";
		chair8.price=7200.00;
		chair8.toSit();
		System.out.println(chair8.name+"\n"+chair8.type+"\n"+chair8.color+"\n"+chair8.price);
		Chair chair9 = new Chair();
		chair9.name="Outdoor Adventure";
		chair9.type="Folding Camping";
		chair9.color="Green";
		chair9.price=1000.00;
		chair9.toSit();
		System.out.println(chair9.name+"\n"+chair9.type+"\n"+chair9.color+"\n"+chair9.price);
	}
}